classes:
- service.kubernetes.pool.cluster
- service.docker.host
- system.kubernetes.common
parameters:
  kubernetes:
    pool:
      network:
        calico:
          prometheus:
            enabled: true
  docker:
    host:
      options:
        iptables: false
        log-opts:
          labels: "io.kubernetes.pod.name"
