classes:
- service.kubernetes.pool.single
- service.docker.host
- system.kubernetes.common
parameters:
  docker:
    host:
      options:
        iptables: false
        log-opts:
          labels: "io.kubernetes.pod.name"
