classes:
- service.cinder.volume.local
- system.salt.minion.cert.mysql.clients.openstack.cinder
parameters:
  _param:
    openstack_mysql_x509_enabled: False
    galera_ssl_enabled: False
  cinder:
    volume:
      enabled: True
      database:
        host: ${_param:single_address}
        x509:
          enabled: ${_param:openstack_mysql_x509_enabled}
          ca_file: ${_param:mysql_cinder_ssl_ca_file}
          key_file: ${_param:mysql_cinder_client_ssl_key_file}
          cert_file: ${_param:mysql_cinder_client_ssl_cert_file}
        ssl:
          enabled: ${_param:galera_ssl_enabled}
      glance:
        host: ${_param:single_address}
      message_queue:
        host: ${_param:single_address}
      identity:
        host: ${_param:single_address}
        region: ${_param:openstack_region}
