parameters:
  _param:
    kubernetes_calico_calicoctl_repo: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico
    kubernetes_calico_repo: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico
    kubernetes_calico_cni_repo: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico
    kubernetes_hyperkube_repo: docker-prod-virtual.docker.mirantis.net/mirantis/kubernetes
    kubernetes_contrail_cni_repo: docker-prod-virtual.docker.mirantis.net/mirantis/kubernetes
    kubernetes_contrail_network_controller_repo: docker-prod-virtual.docker.mirantis.net/mirantis/kubernetes/contrail-integration
    kubernetes_netchecker_agent_repo: mirantis
    kubernetes_netchecker_server_repo: mirantis
    kubernetes_virtlet_repo: mirantis
    kubernetes_kubedns_repo: gcr.io/google_containers
    kubernetes_externaldns_repo: mirantis
    kubernetes_genie_repo: https://artifactory.mcp.mirantis.net/artifactory/binary-prod-local/mirantis/kubernetes/cni-genie
    kubernetes_flannel_repo: quay.io/coreos
    kubernetes_metallb_repo: metallb
    kubernetes_sriov_repo: https://artifactory.mcp.mirantis.net/artifactory/binary-prod-local/mirantis/kubernetes/sriov-cni
    kubernetes_cniplugins_repo: https://artifactory.mcp.mirantis.net/artifactory/binary-prod-local/mirantis/kubernetes/containernetworking-plugins

    # component docker images
    kubernetes_docker_package: docker-engine=1.13.1-0~ubuntu-xenial
    kubernetes_calico_calicoctl_image: ${_param:kubernetes_calico_calicoctl_repo}/ctl:v1.6.4
    kubernetes_calico_image: ${_param:kubernetes_calico_repo}/node:v2.6.10
    kubernetes_calico_cni_image: ${_param:kubernetes_calico_cni_repo}/cni:v1.11.6
    kubernetes_hyperkube_image: ${_param:kubernetes_hyperkube_repo}/hyperkube-amd64:v1.10.4-4
    kubernetes_pause_image: ${_param:kubernetes_hyperkube_repo}/pause-amd64:v1.10.4-4
    kubernetes_contrail_cni_image: ${_param:kubernetes_contrail_cni_repo}/contrail-cni:v1.2.0
    kubernetes_contrail_network_controller_image: ${_param:kubernetes_contrail_network_controller_repo}/contrail-network-controller:v1.2.0
    kubernetes_virtlet_image: ${_param:kubernetes_virtlet_repo}/virtlet:v1.1.1
    kubernetes_criproxy_version: v0.11.1
    kubernetes_criproxy_checksum: md5=a3f1f08bdc7a8d6eb73b7c8fa5bae200
    kubernetes_netchecker_agent_image: ${_param:kubernetes_netchecker_agent_repo}/k8s-netchecker-agent:v1.2.2
    kubernetes_netchecker_server_image: ${_param:kubernetes_netchecker_server_repo}/k8s-netchecker-server:v1.2.2
    kubernetes_kubedns_image: ${_param:kubernetes_kubedns_repo}/k8s-dns-kube-dns-amd64:1.14.5
    kubernetes_dnsmasq_image: ${_param:kubernetes_kubedns_repo}/k8s-dns-dnsmasq-amd64:1.14.5
    kubernetes_sidecar_image: ${_param:kubernetes_kubedns_repo}/k8s-dns-sidecar-amd64:1.14.5
    kubernetes_dns_autoscaler_image: ${_param:kubernetes_kubedns_repo}/cluster-proportional-autoscaler-amd64:1.0.0
    kubernetes_externaldns_image: ${_param:kubernetes_externaldns_repo}/external-dns:v0.5.3
    kubernetes_genie_source: ${_param:kubernetes_genie_repo}/genie_v1.0-138-gbf5dbaa
    kubernetes_genie_source_hash: md5=b024052ed4ecb1d5354e0cc8f51afaca
    kubernetes_flannel_image: ${_param:kubernetes_flannel_repo}/flannel:v0.10.0-amd64
    kubernetes_metallb_controller_image: ${_param:kubernetes_metallb_repo}/controller:v0.6.2
    kubernetes_metallb_speaker_image: ${_param:kubernetes_metallb_repo}/speaker:v0.6.2
    kubernetes_sriov_source: ${_param:kubernetes_sriov_repo}/sriov_v0.3-8-g8b7ed98
    kubernetes_sriov_source_hash: md5=c0cc33202afd02e4cc44b977a8faf6e7
    kubernetes_cniplugins_source: ${_param:kubernetes_cniplugins_repo}/cni-plugins_v0.7.1-48-g696b1f9.tar.gz
    kubernetes_cniplugins_source_hash: md5=5ec1cf5e989097c6127ea5365e277b02

    kubelet_fail_on_swap: true
    kubernetes_kubedns_enabled: true
    kubernetes_externaldns_enabled: false
    kubernetes_coredns_enabled: false
    kubernetes_externaldns_provider: coredns
    kubernetes_virtlet_enabled: false
    kubernetes_flannel_enabled: false
    kubernetes_genie_enabled: false
    kubernetes_calico_enabled: false
    kubernetes_opencontrail_enabled: false
    kubernetes_contrail_network_controller_enabled: false
    kubernetes_metallb_enabled: false
    kubernetes_sriov_enabled: false

  docker:
    host:
      pkgs:
        - ${_param:kubernetes_docker_package}
        - python-docker
      options:
        bip: 172.31.255.1/24
        storage-driver: overlay2

  kubernetes:
    common:
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
        pause_image: ${_param:kubernetes_pause_image}
      cni:
        plugins:
          source: ${_param:kubernetes_cniplugins_source}
          hash: ${_param:kubernetes_cniplugins_source_hash}
      addons:
        dns:
          enabled: ${_param:kubernetes_kubedns_enabled}
          kubedns_image: ${_param:kubernetes_kubedns_image}
          dnsmasq_image: ${_param:kubernetes_dnsmasq_image}
          sidecar_image: ${_param:kubernetes_sidecar_image}
          autoscaler:
            image: ${_param:kubernetes_dns_autoscaler_image}
        externaldns:
          enabled: ${_param:kubernetes_externaldns_enabled}
          namespace: kube-system
          image: ${_param:kubernetes_externaldns_image}
          provider: ${_param:kubernetes_externaldns_provider}
        coredns:
          enabled: ${_param:kubernetes_coredns_enabled}
        contrail_network_controller:
          enabled: ${_param:kubernetes_contrail_network_controller_enabled}
          image: ${_param:kubernetes_contrail_network_controller_image}
        flannel:
          enabled: ${_param:kubernetes_flannel_enabled}
          image: ${_param:kubernetes_flannel_image}
        virtlet:
          enabled: ${_param:kubernetes_virtlet_enabled}
          namespace: kube-system
          image: ${_param:kubernetes_virtlet_image}
          criproxy_version: ${_param:kubernetes_criproxy_version}
          criproxy_source: ${_param:kubernetes_criproxy_checksum}
        metallb:
          enabled: ${_param:kubernetes_metallb_enabled}
    master:
      enabled: false
      kubelet:
        fail_on_swap: ${_param:kubelet_fail_on_swap}
      container: false
      network:
        genie:
          enabled: ${_param:kubernetes_genie_enabled}
          source: ${_param:kubernetes_genie_source}
          source_hash: ${_param:kubernetes_genie_source_hash}
        calico:
          enabled: ${_param:kubernetes_calico_enabled}
          image: ${_param:kubernetes_calico_image}
          calicoctl_image: ${_param:kubernetes_calico_calicoctl_image}
          cni_image: ${_param:kubernetes_calico_cni_image}
        opencontrail:
          enabled: ${_param:kubernetes_opencontrail_enabled}
          cni_image: ${_param:kubernetes_contrail_cni_image}
        sriov:
          enabled: ${_param:kubernetes_sriov_enabled}
          source: ${_param:kubernetes_sriov_source}
          source_hash: ${_param:kubernetes_sriov_source_hash}
    pool:
      enabled: false
      kubelet:
        fail_on_swap: ${_param:kubelet_fail_on_swap}
      container: false
      network:
        genie:
          enabled: ${_param:kubernetes_genie_enabled}
          source: ${_param:kubernetes_genie_source}
          source_hash: ${_param:kubernetes_genie_source_hash}
        calico:
          enabled: ${_param:kubernetes_calico_enabled}
          image: ${_param:kubernetes_calico_image}
          calicoctl_image: ${_param:kubernetes_calico_calicoctl_image}
          cni_image: ${_param:kubernetes_calico_cni_image}
        opencontrail:
          enabled: ${_param:kubernetes_opencontrail_enabled}
          cni_image: ${_param:kubernetes_contrail_cni_image}
        sriov:
          enabled: ${_param:kubernetes_sriov_enabled}
          source: ${_param:kubernetes_sriov_source}
          source_hash: ${_param:kubernetes_sriov_source_hash}
